services:

  configserver:
    image: adiazarroyo/configserver:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - adiaz-network

  eurekaserver:
    image: adiazarroyo/eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - adiaz-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 240s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  accounts:
    image: adiazarroyo/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8000"
    networks:
      - adiaz-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 240s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka

  loans:
    image: adiazarroyo/loans:latest
    mem_limit: 700m
    ports:
      - "8081:8100"
    networks:
      - adiaz-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 240s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka

  cards:
    image: adiazarroyo/cards:latest
    mem_limit: 700m
    ports:
      - "8082:8200"
    networks:
      - adiaz-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 240s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka

networks:
  adiaz-network: